version: "3"

services:
  jgt-jupyter-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
  jupyter:
    image: jupyter/scipy-notebook:lab-4.0.7
    command: jupyter lab --NotebookApp.token='' --NotebookApp.open_browser='False' --NotebookApp.disable_check_xsrf='True' 
    container_name: jupyter_embedded_dd_vm
    restart: unless-stopped
    volumes:
      - jgt_jupyter_data:/home/jovyan
    environment:
      TZ: America/Argentina/Buenos_Aires
    ports:
      - 58888:8888
volumes:
  jgt_jupyter_data:
